### ISSUE TITLE
Cuda + GPU causes error in baking

### ISSUE THREAD

**Issue by tlaukkan** [danielenger/Principled-Baker#1]
Hi

I am not sure if this is supposed to be supported but selecting Cuda + GPU for cycles causes error in baking:

Runtime Error Cuda Error...

**Comment by danielenger** [comment]
I had the same issue. I think this is a bug with blender 2.80 beta.
The baking itself is done by blender.

**Comment by danielenger** [comment]
I circumvented the issue for now, but I let this issue open.
