### ISSUE TITLE
Not working with Blender 2.9

### ISSUE THREAD

**Issue by slayermaster** [danielenger/Principled-Baker#14]
Just informing that this does not work on 2.9, if anybody wondering.

**Comment by muhuk** [comment]
I am getting the following error:

```python
Traceback (most recent call last):
  File "/home/muhuk/.config/blender/2.90/scripts/addons/Principled-Baker-master/pbaker_bake.py", line 1924, in execute
    self.job_name), selected_to_active=True)
  File "/home/muhuk/.config/blender/2.90/scripts/addons/Principled-Baker-master/pbaker_bake.py", line 870, in bake_and_save
    self.save_image(image)
  File "/home/muhuk/.config/blender/2.90/scripts/addons/Principled-Baker-master/pbaker_bake.py", line 131, in save_image
    exr_codec=self.settings.exr_codec)
  File "/home/muhuk/.config/blender/2.90/scripts/addons/Principled-Baker-master/pbaker_functions.py", line 261, in save_image_as
    bpy.context.scene.view_settings.view_transform = defalut_vt
TypeError: bpy_struct: item.attr = val: enum "Default" not found in ('Standard', 'Filmic', 'Filmic Log', 'Raw', 'False Color')

location: <unknown location>:-1

```

Renderer is set to cycles, color management is Filmic.

**Comment by SariaFace** [comment]
The problem with 2.9+ incompatibility is several lines in two scripts that misidentify 2.9+ as 2.79 and lower.
For fresh installs this will cause a registration error and script loading will completely fail.
For installs which remained after upgrade, it will cause various aberrant behaviour, (e.g. bake list inaccessible)
These issues can be solved with these changes to the following two script files.

**pbaker_functions.py**, lines 7 and 8:
```python
is_2_79 = True if bpy.app.version_string.startswith('2.7') else False
is_2_80 = True if bpy.app.version_string.startswith('2.8') else False
```
should be changed to
```python
is_2_79 = True if bpy.app.version < ( 2, 80, 0) else False
is_2_80 = True if bpy.app.version >= ( 2, 80, 0) else False
```

**__init__.py**, line 37:
```python
if bpy.app.version_string.startswith('2.8'):
```
should be changed to
```python
if bpy.app.version >= ( 2, 80, 0):
```

**Comment by plufz** [comment]
@SariaFace thanks alot!

**Comment by danielenger** [comment]
Thanks!
I applied it as a quick fix till I'm done with the update.

**Comment by lumpy668** [comment]
Hi
The new file: "Principled-Baker-dcfe31b1dbb727603303b6aa0cbc113752c2f8d5" or "Merge pull request" is still not working for me  :(
Any idea of when this is gonna be working?

**Comment by MeshVoid** [comment]
Sadly, recent fixes don't work for me with Blender 2.90.1 on Windows 10, all I get is blank images with correct filenames but no image information. I don't get any errors at all, it all seems like the baking was completed successfully, but it isn't. Manual baking via the built-in baking system in Blender works correctly. But Principled baker addon just refuses to work no matter what I do and what file format or texture type I choose :(.

**Comment by Alekzs89** [comment]
The Baker still don't work on 2.9

`Traceback (most recent call last):
  File "C:\Users\A\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Principled-Baker-master\baker.py", line 871, in execute
    self.bake_batch(context, self.bake_objects)
  File "C:\Users\A\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Principled-Baker-master\baker.py", line 627, in bake_batch
    self.bake_combined(context, [obj])
  File "C:\Users\A\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Principled-Baker-master\baker.py", line 564, in bake_combined
    bake_type=get_bake_type_by(self.jobname))
  File "C:\Users\A\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Principled-Baker-master\baker.py", line 293, in bake_and_save
    image.save()
RuntimeError: Error: Image 'attore_color.png' could not be saved to '\attore_color.png'


location: <unknown location>:-1`

**Comment by Markdove86** [comment]
Fails to create files in 2.9 windows 10 randomly sometimes it manages to create normal maps...

**Comment by HarrierCZ** [comment]
Same issue, plugin cannot save images in 2.90.1.
Is something wrong with output path? I am missing colon after hdd letter.


Error: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Principled-Baker-master\baker.py", line 869, in execute
    self.bake_combined(context, self.bake_objects)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Principled-Baker-master\baker.py", line 564, in bake_combined
    bake_type=get_bake_type_by(self.jobname))
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Principled-Baker-master\baker.py", line 293, in bake_and_save
    image.save()
RuntimeError: Error: Image 'CAR_metallic.png' could not be saved to 'D\car\CAR_metallic.png'

**Comment by rififa11** [comment]
Same here, but I did test some things and I've got it to work. I have Blender 2.90.1 and Windows 10.

I choose my file path (for example when I click on the file button to pick my destination folder), then I bake but I always have the same error message, but I noticed something about the path : the "C:\" became "C\" in the file path and also on the error message. When I tested some other path, I found that you can replace "C:\" with "\" and it will be understand the same, but this time without any error !

So when you choose your file path, just replace "C:\your\file\path\" with "\your\file\path\" and it work just fine for me 😄

**Comment by Alekzs89** [comment]
> So when you choose your file path, just replace "C:\your\file\path" with "\your\file\path" and it work just fine for me 😄

That actually works. Thank you very much.

**Comment by SmittyWerbenJJ** [comment]
> So when you choose your file path, just replace "C:\your\file\path" with "\your\file\path" and it work just fine for me 😄
Unfortunately that does not work for me. I tried putting in the path like you suggested but it does not find it:

![errorMessage](https://user-images.githubusercontent.com/35438764/102985543-99acd980-450f-11eb-8e64-784e962fe112.png)

The path exists and I'm allowrd to write files in it:
![image](https://user-images.githubusercontent.com/35438764/102985707-e7c1dd00-450f-11eb-9c11-705da91e8579.png)

Also how can the code detect a path on a different Hard Drive, when we have to keep out the drive letter in the path?
I'm mostly working on a different Hard drive "D:\" , so everytime I would have to bake the images on the C drive, then move them to the "D:\" drive and also reload the images in blender nodes.

Is there maybe way to go around this all this?

**Comment by slayermaster** [comment]
Tried on 2.92 and it installs fine, runs fine and bakes just fine. There is file path problem discussed here, but I guess that needs it's own issue. For now, just use // as path so it bakes on the same directory as .blend file.
