### ISSUE TITLE
Bake Error: Image 'name.png' could not be saved to '\name.png' [Blender 2.83]

### ISSUE THREAD

**Issue by Castrilicus** [danielenger/Principled-Baker#16]
Hello
I'm trying to bake a mesh I made but I keep running into this error

```
||Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\Principled-Baker-master\baker.py", line 869, in execute
    self.bake_combined(context, self.bake_objects)
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\Principled-Baker-master\baker.py", line 564, in bake_combined
    bake_type=get_bake_type_by(self.jobname))
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\Principled-Baker-master\baker.py", line 293, in bake_and_save
    image.save()
RuntimeError: Error: Image 'Plane_color.png' could not be saved to '\Plane_color.png'


location: <unknown location>:-1
```

**Comment by remictrr** [comment]
Yeah i also got the same error. I tried in blender 2.83 and 2.9 and the error is still there. If you found a solution, please post it here. I will do the same if i find one.

**Comment by Castrilicus** [comment]
> Yeah i also got the same error. I tried in blender 2.83 and 2.9 and the error is still there. If you found a solution, please post it here. I will do the same if i find one.


**Solution**
The error is being caused by the double slashes "//" present in the beginning of the output path.
Replace it with a single slash "/" and enter your output directory
Example:-
"/C:/Users/Admin/.."


I hope the info was useful 🙂

**Comment by remictrr** [comment]
I tried this but it dosen't work for me. I've tried relatives and absolutes paths sevral times but none of them works.

**Comment by remictrr** [comment]
well, as the addon doesn't want to save the images, i just removed the saving line in the addon and it worked. now i need to save the images manually but at least it work. To do the same, just replace this function:
`def bake_and_save(self, image, bake_type='EMIT'):
		"""Bake and save image."""
		
		image.save()
		self.report({'INFO'}, "baking '{0}'".format(image.name))
		self.bake(bake_type)
		save_image(image, self.get_color_mode(self.jobname))
		image.reload()`
by this one:
`def bake_and_save(self, image, bake_type='EMIT'):
		"""Bake and save image."""

		self.report({'INFO'}, "baking '{0}'".format(image.name))
		self.bake(bake_type)
		save_image(image, self.get_color_mode(self.jobname))`
in the file here: C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\Principled-Baker-master\baker.py, 
line 290

**Comment by Castrilicus** [comment]
I'll close this issue since it is solved. 

**Solution 1** 

> The error is being caused by the double slashes '\\' present in the beginning of the output path.
> Replace it with a single slash " \" and enter your output directory
> Example:-
> "\C:\Users\Admin\.."
> 
> I hope the info was useful 🙂

The output path should start with a single slash "\"
Screenshot: https://gyazo.com/e0b2d221d1a6e9b4b1d194c139e6c79a

If it still gives an error, try what remictrr suggested,
**Solution 2**
> well, as the addon doesn't want to save the images, i just removed the saving line in the addon and it worked. now i need to save the images manually but at least it work. To do the same, just replace this function:
> `def bake_and_save(self, image, bake_type='EMIT'):
> """Bake and save image."""
> 
> ```
> 	image.save()
> 	self.report({'INFO'}, "baking '{0}'".format(image.name))
> 	self.bake(bake_type)
> 	save_image(image, self.get_color_mode(self.jobname))
> 	image.reload()`
> ```
> 
> by this one:
> `def bake_and_save(self, image, bake_type='EMIT'):
> """Bake and save image."""
> 
> ```
> 	self.report({'INFO'}, "baking '{0}'".format(image.name))
> 	self.bake(bake_type)
> 	save_image(image, self.get_color_mode(self.jobname))`
> ```
> 
> in the file here: C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\Principled-Baker-master\baker.py,
> line 290
