### ISSUE TITLE
I'm getting this installation error with v2.79 on macOS Mojave

### ISSUE THREAD

**Issue by untmdsprt** [danielenger/Principled-Baker#3]
<img width="782" alt="screen shot 2019-01-05 at 13 54 43" src="https://user-images.githubusercontent.com/10523925/50728573-a8ffa600-10f1-11e9-8cfc-c13c6766d62f.png">

I downloaded direct from your GitHub as a zip file.

**Comment by danielenger** [comment]
You can find the add-on for blender v2.79 here: https://github.com/danielenger/Principled-Baker_for_2-79

I split the add-on because of the changes in blender 2.80.
I'm not developing the add-on for 2.79 further. But if it's needed for 2.79, I can make a backport.

**Comment by untmdsprt** [comment]
Thanks. I believe I've gotten it up and running now. I'm slowly making the switch to 2.8 myself.
