### ISSUE TITLE
Light baking

### ISSUE THREAD

**Issue by Sembei** [danielenger/Principled-Baker#4]
Would be possible to add direct/indirect light baking ?

**Comment by danielenger** [comment]
Do you mean diffuse direct/indirect (bake_type=Diffuse with render.bake.use_pass_direct/render.bake.use_pass_indirect)?
Are there any (quasi) standards for the suffixes? Like "_diffuse_direct" or something like that? I ask for good default names.

I can build that in one of the next updates.

**Comment by Sembei** [comment]
Yes that or use the combined pass, it's just to plug it on game engines as baked light.  I'm not aware of any naming convention, just something that matches would be enough.

**Comment by danielenger** [comment]
I made a quick implementation. For the time beeing it can only bake one pass at once.

**Comment by Sembei** [comment]
Nice! , I'll take a look

**Comment by Sembei** [comment]
Could be that Diffuse baking to png is in linear space instead of sRGB?

**Comment by danielenger** [comment]
It's fixed.
Diffuse should be in sRGB, as far as I know.

**Comment by Sembei** [comment]
For non float formats yes
