### ISSUE TITLE
Automate baking with python

### ISSUE THREAD

**Issue by KarlMoellerDev** [danielenger/Principled-Baker#7]
I am trying to autmate the baking process from a python script. So far I am able to successfully configure the bake:
```python
bpy.context.scene.principled_baker_settings.resolution = '1024'
bpy.context.scene.principled_baker_bakelist[0].do_bake = True
bpy.context.scene.principled_baker_bakelist[1].do_bake = True
bpy.context.scene.principled_baker_bakelist[2].do_bake = True
bpy.context.scene.principled_baker_settings.file_path = "//PBR Bake\\Test\\"
```
however, I am unable to start the actual bake. I have tried
```python
bpy.ops.object.principled_baker_bake()
```
but the bake process does not seem to start. The object is selected and the bake works without problems once I press the bake button manually. Is there something I am missing or is there a better approach?

**Comment by deltamish** [comment]
Any luck ? even i am trying to do the same.

**Comment by KarlMoellerDev** [comment]
Sadly no luck so far. I stopped working on the script back in november. I will post an update if I ever get back to it.

**Comment by danielenger** [comment]
You can give it a try now.
Running 'bpy.ops.object.principled_baker_bake()' from console works since 0.5.5, again.
